### ISSUE TITLE
NoMethodError `undefined method `exitstatus' for nil:NilClass`

### ISSUE THREAD

**Issue by zerogee00** [arya/bluepill#207]
When running Bluepill under ruby 2.2.2 I get this error:

```Failed to start bluepill:
NoMethodError `undefined method `exitstatus' for nil:NilClass`
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/system.rb:200:in `execute_blocking'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/process.rb:294:in `block in start_process'
/pkg/ruby-lang.org/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/pkg/ruby-lang.org/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
/pkg/ruby-lang.org/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/pkg/ruby-lang.org/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/pkg/ruby-lang.org/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/process.rb:510:in `with_timeout'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/process.rb:293:in `start_process'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/eval_helpers.rb:58:in `evaluate_method'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/callback.rb:191:in `block in run_methods'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/callback.rb:190:in `each'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/callback.rb:190:in `run_methods'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/callback.rb:159:in `call'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `block (2 levels) in after'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `each'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `block in after'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:448:in `catch'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:448:in `after'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:251:in `run_callbacks'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:127:in `run_callbacks'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `catch'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block in perform'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:182:in `block in within_transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:227:in `block in within_transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/machine.rb:1902:in `block in within_transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/machine.rb:2222:in `transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/machine.rb:1902:in `within_transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:226:in `within_transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:181:in `within_transaction'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:62:in `perform'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/transition.rb:219:in `perform'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/event.rb:172:in `fire'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/event.rb:247:in `block in add_actions'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `call'
/frm/ruby/2.2.2/lib/ruby/gems/2.2.2/gems/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `block (2 levels) in define_helper'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/process.rb:158:in `tick'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/group.rb:18:in `each'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/group.rb:18:in `tick'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:149:in `block (2 levels) in run'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:149:in `each'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:149:in `block in run'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:40:in `synchronize'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:40:in `mutex'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:147:in `run'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:141:in `start_server'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/application.rb:44:in `load'
/srv/httpd/gems/gems/bluepill-0.1.1/lib/bluepill/dsl.rb:9:in `application'```

which seems to stem from `exit_code: $CHILD_STATUS.exitstatus,` in system.rb. 

Has anyone else seen this? If I run the process directly it runs fine.

**Comment by pahnin** [comment]
same with me

**Comment by akzhan** [comment]
looks like it fixed in https://github.com/bluepill-rb/bluepill/commit/eda6bf0d86752be51a73fab59b746e26194e377e

**Comment by pahnin** [comment]
@akzhan thanks for the quick response, I tried installing gem from github and I do have the changes https://github.com/bluepill-rb/bluepill/commit/eda6bf0d86752be51a73fab59b746e26194e377e
but I can't start bluepill :cry: controller doesn't even come in the stacktrace, @zerogee00 and I have the same stack trace. 
I have searched $CHILD_STATUS on google and it looks like it is a default variable set by ruby!? If $CHILD_STATUS is not being set, does that mean the processes are not running?

**Comment by julioolvr** [comment]
In my case, doing a `require 'English'` on my pill file fixed it. It seems that Bluepill relies on that, maybe it should be required by the gem, or `$?` should be used instead?

**Comment by akzhan** [comment]
@julioolvr can you provide PR with `$?` I will merge it. This is because I temporarily w/o mac.

**Comment by julioolvr** [comment]
You got it https://github.com/bluepill-rb/bluepill/pull/43

**Comment by pahnin** [comment]
thanks @julioolvr @akzhan
